### ISSUE TITLE
Can I support relaying multiple SMTP servers?

### ISSUE THREAD

**Issue by dragonhackertel** [grafana/smtprelay#129]
Can I support relaying multiple SMTP servers?

**Comment by hairyhenderson** [comment]
Hi @dragonhackertel, thanks for your question.

This relay will only send e-mail _to_ a single SMTP server. However, it supports relaying messages from any number of MTAs (Message Transfer Agents, either SMTP clients or SMTP servers).

I'm going to consider your question answered. If not, feel free to re-open and clarify.
