### ISSUE TITLE
Submit our work to upstream

### ISSUE THREAD

**Issue by electron0zero** [grafana/smtprelay#15]
We would like to upstream our work, we can upstream:

- [x] Code changes, see https://github.com/decke/smtprelay/pull/13
- [ ] k8s deployment example
- [ ] Grafana Dashboards
- [ ] Alerts

**Comment by hairyhenderson** [comment]
I'm going to close this for now, given the drift that's happened over the past 2 years... Some of the changes from that original PR were brought upstream (in separate PRs), but it'll still take quite some effort to upstream everything.

I still think upstreaming is a good ultimate goal, but will likely involve too much effort to complete.
